[package]
name = "shiqu"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide = { version = "0.13", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version =  "1.43", features = ["rt-multi-thread", "macros"] }
